### ISSUE TITLE
Unable to successfully build Python bindings

### ISSUE THREAD

**Issue by travisbrady** [facebookresearch/StarSpace#255]
I've now tried building the bindings on my OSX and Linux (within a Docker container) to no avail.

In all cases I get the dreaded pybind11 `Symbol not found: __Py_ZeroStruct` error, but even after following instructions at https://pybind11.readthedocs.io/en/stable/faq.html and https://github.com/openai/retro/issues/75 I'm still not able to successfully build.

Does anyone have an example setup or Docker file that has allowed you to build successfully?
Have you used vanilla python? Anaconda? Something else?

*Full Output*:
```
./build.sh
############################# initial cleanup #############################
#############################  build starspace #############################
rm -rf *.o starspace gtest.a gtest_main.a *_test query_nn print_ngrams
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -g -c src/utils/normalize.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/dict.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -g -c src/utils/args.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/proj.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/parser.cpp -o parser.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/data.cpp -o data.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/model.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/starspace.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/doc_parser.cpp -o doc_parser.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/doc_data.cpp -o doc_data.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/utils/utils.cpp -o utils.o
ar rcs libstarspace.a normalize.o dict.o args.o proj.o parser.o data.o model.o starspace.o doc_parser.o doc_data.o utils.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libstarspace.a(proj.o) has no symbols
/Users/tbrady/code/hub/StarSpace/python
#############################  build wrapper #############################
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=8.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    pybind11/2.2.4@conan/stable from 'conan-center' - Cache
Packages
    pybind11/2.2.4@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

pybind11/2.2.4@conan/stable: Already installed!
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10")
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tbrady/code/hub/StarSpace/python/build
Scanning dependencies of target starwrap
[ 50%] Building CXX object CMakeFiles/starwrap.dir/starspace_pybind.cc.o
[100%] Linking CXX shared library starwrap.so
[100%] Built target starwrap
/Users/tbrady/code/hub/StarSpace/python
#############################  run test #############################
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import starwrap as sw
ImportError: dlopen(/Users/tbrady/code/hub/StarSpace/python/test/starwrap.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/tbrady/code/hub/StarSpace/python/test/starwrap.so
  Expected in: flat namespace
 in /Users/tbrady/code/hub/StarSpace/python/test/starwrap.so
```

**Comment by aristako** [comment]
I'm having the exact same issue. I have tried following all steps in both a Python 2.7 venv as well as a 3.6+. Have you had any updates since originally posting? 

I am about to try a fresh clone + install to see if it fixes anything.

**Comment by aristako** [comment]
On a fresh install, I am getting a different but seemingly similar error. 

```
############################# initial cleanup #############################
#############################  build starspace #############################
rm -rf *.o starspace gtest.a gtest_main.a *_test query_nn print_ngrams
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -g -c src/utils/normalize.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/dict.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -g -c src/utils/args.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/proj.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/parser.cpp -o parser.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/data.cpp -o data.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/model.cpp
In file included from src/model.cpp:10:
In file included from /usr/local/bin/boost_1_63_0/boost/archive/binary_iarchive.hpp:20:
In file included from /usr/local/bin/boost_1_63_0/boost/archive/binary_iarchive_impl.hpp:21:
In file included from /usr/local/bin/boost_1_63_0/boost/archive/basic_binary_iarchive.hpp:30:
In file included from /usr/local/bin/boost_1_63_0/boost/archive/detail/common_iarchive.hpp:23:
In file included from /usr/local/bin/boost_1_63_0/boost/archive/detail/interface_iarchive.hpp:22:
/usr/local/bin/boost_1_63_0/boost/archive/detail/iserializer.hpp:69:7: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if ! DONT_USE_HAS_NEW_OPERATOR
      ^
/usr/local/bin/boost_1_63_0/boost/archive/detail/iserializer.hpp:63:12: note: expanded from macro 'DONT_USE_HAS_NEW_OPERATOR'
        || defined(__SUNPRO_CC) && (__SUNPRO_CC < 0x590)   \
           ^
/usr/local/bin/boost_1_63_0/boost/archive/detail/iserializer.hpp:212:9: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
    #if DONT_USE_HAS_NEW_OPERATOR
        ^
/usr/local/bin/boost_1_63_0/boost/archive/detail/iserializer.hpp:63:12: note: expanded from macro 'DONT_USE_HAS_NEW_OPERATOR'
        || defined(__SUNPRO_CC) && (__SUNPRO_CC < 0x590)   \
           ^
2 warnings generated.
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/starspace.cpp
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/doc_parser.cpp -o doc_parser.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/doc_data.cpp -o doc_data.o
g++ -pthread -std=gnu++11 -O3 -fPIC -funroll-loops -I/usr/local/bin/boost_1_63_0/ -g -c src/utils/utils.cpp -o utils.o
ar rcs libstarspace.a normalize.o dict.o args.o proj.o parser.o data.o model.o starspace.o doc_parser.o doc_data.o utils.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libstarspace.a(proj.o) has no symbols
/Users/arianastassiou/Dissertation/StarSpace/python
#############################  build wrapper #############################
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    pybind11/2.2.4@conan/stable from 'conan-center' - Cache
Packages
    pybind11/2.2.4@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

pybind11/2.2.4@conan/stable: Already installed!
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (found version "3.7.3")
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arianastassiou/Dissertation/StarSpace/python/build
Scanning dependencies of target starwrap
[ 50%] Building CXX object CMakeFiles/starwrap.dir/starspace_pybind.cc.o
[100%] Linking CXX shared library starwrap.so
[100%] Built target starwrap
/Users/arianastassiou/Dissertation/StarSpace/python
#############################  run test #############################
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import starwrap as sw
ImportError: dlopen(/Users/arianastassiou/Dissertation/StarSpace/python/test/starwrap.so, 2): Symbol not found: _PyThread_tss_alloc
  Referenced from: /Users/arianastassiou/Dissertation/StarSpace/python/test/starwrap.so
  Expected in: flat namespace
 in /Users/arianastassiou/Dissertation/StarSpace/python/test/starwrap.so
/Users/arianastassiou/Dissertation/StarSpace/python
```

**Comment by aristako** [comment]
@travisbrady I fixed my problem, I hope it can help you as well.

I commented out lines #29-36 in the CMakeLists.txt (I think this only exists if you run the `./build.sh` command and it fails as above. 

More importantly, change the following line in `build.sh`:
```
-cmake .. -DCMAKE_BUILD_TYPE=Release
+cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=/anaconda3/envs/mlp/lib/libpython3.6m.dylib -DPYTHON_INCLUDE_DIR=/anaconda3/envs/mlp/include/python3.6m/
```

The two paths above are specific for me, but must point to the environment you are using (or wanting to use).

**Comment by AkaneNyan** [comment]
Duplicate of #232

**Comment by travisbrady** [comment]
It worked! Thanks very much, @aristako! Now to get this fixed in master
